export const QUESTIONS = [
  {
    id: 1,
    text: 'Edad (introduce solo el valor numérico):',
    type: 'text',
    field: 'age',
    nextStep: 2,
  },
  {
    id: 2,
    text: 'Género:',
    type: 'radio',
    field: 'gender',
    options: [
      { label: 'Masculino', value: 'male' },
      { label: 'Femenino', value: 'female' },
      { label: 'Otro', value: 'other' },
    ],
    nextStep: 3,
  },
  {
    id: 3,
    text: 'Curso y grupo:',
    type: 'radio',
    field: 'group',
    options: [
      { label: '4ªESO A', value: '4ESO_A' },
      { label: '4ªESO B', value: '4ESO_B' },
      { label: '4ªESO C', value: '4ESO_C' },
      { label: '1ºBACH A', value: '1BACH_A' },
      { label: '1ºBACH B', value: '1BACH_B' },
      { label: '1ºBACH C', value: '1BACH_C' },
      { label: '1ºBACH D', value: '1BACH_D' },
      { label: '1ºBACH E', value: '1BACH_E' },
      { label: '1ºBACH F', value: '1BACH_F' },
      { label: '2ºBACH A', value: '2BACH_A' },
      { label: '2ºBACH A', value: '2BACH_B' },
      { label: '2ºBACH B', value: '2BACH_C' },
      { label: '2ºBACH D', value: '2BACH_D' },
      { label: '2ºBACH E', value: '2BACH_E' },
      { label: '2ºBACH F', value: '2BACH_F' },
    ],
    nextStep: 4,
  },
  {
    id: 4,
    text: 'Si tienes alguna duda sobre sexualidad, ¿a quién recurres?',
    type: 'radio',
    field: 'source',
    options: [
      { label: 'Madre', value: 'mother' },
      { label: 'Padre', value: 'father' },
      { label: 'Tutor legal', value: 'legal_tutor' },
      { label: 'Tutora legal', value: 'legal_tutress' },
      { label: 'Amigos', value: 'friends' },
      { label: 'Redes sociales', value: 'social_media' },
      { label: 'Google', value: 'google' },
      { label: 'Otro', value: 'otro' },
    ],
    nextStep: (value: string) => (value === 'otro' ? 5 : 6),
  },
  {
    id: 5,
    text: 'Especifica a quién recurres:',
    type: 'text',
    field: 'specific_source',
    nextStep: 6,
  },
  {
    id: 6,
    text: '¿Con qué frecuencia hablas sobre sexualidad con tus padres/tutores?',
    type: 'radio',
    field: 'parent_talk_frequency',
    options: [
      { label: 'Nada', value: 'none' },
      { label: 'Poco', value: 'little' },
      { label: 'Más o menos', value: 'moderate' },
      { label: 'Bastante', value: 'much' },
      { label: 'Mucho', value: 'a_lot' },
    ],
    nextStep: 7,
  },
  {
    id: 7,
    text: '¿A qué edad tuviste tu primera conversación sobre temas sexuales con tus padres/tutores?',
    type: 'text',
    field: 'first_conversation_age',
    nextStep: 8,
  },
  {
    id: 8,
    text: '¿Con qué frecuencia hablas de sexualidad con tus amigos?',
    type: 'radio',
    field: 'friend_talk_frequency',
    options: [
      { label: 'Nada', value: 'none' },
      { label: 'Poco', value: 'little' },
      { label: 'Más o menos', value: 'moderate' },
      { label: 'Bastante', value: 'much' },
      { label: 'Mucho', value: 'a_lot' },
    ],
    nextStep: 9,
  },
  {
    id: 9,
    text: '¿Has visto pornografía alguna vez?',
    type: 'radio',
    field: 'watched_porn',
    options: [
      { label: 'Sí', value: 'yes' },
      { label: 'No', value: 'no' },
    ],
    nextStep: (value: string) => (value === 'yes' ? 10 : 11),
  },
  {
    id: 10,
    text: '¿A qué edad viste pornografía por primera vez?',
    type: 'text',
    field: 'first_porn_age',
    nextStep: 11,
  },
  {
    id: 11,
    text: 'Indica si has hablado en alguna ocasión con tus padres/tutor sobre los siguientes temas:',
    type: 'matrix',
    field: 'parent_topics',
    topics: [
      'Drogas y consumo excesivo de alcohol',
      'Cambios en el cuerpo (p.ej., menstruación, cambios de voz, etc.)',
      'VIH (Sida) y otras ITS (Infecciones de Transmisión Sexual)',
      'Embarazos no deseados',
      'Preservativo',
      'Otros métodos anticonceptivos',
      'Cómo saber cuándo estaré preparado para mantener relaciones sexuales',
    ],
    levels: ['Nada', 'Casi nada', 'Más o menos', 'Bastante', 'Mucho'],
    nextStep: 12,
  },
  {
    id: 12,
    text: 'Indica si en el instituto te han hablado acerca de los siguientes temas:',
    type: 'matrix',
    field: 'school_topics',
    topics: [
      'Drogas y consumo excesivo de alcohol',
      'Cambios en el cuerpo (p.ej., menstruación, cambios de voz, etc.)',
      'VIH (Sida) y otras ITS (Infecciones de Transmisión Sexual)',
      'Embarazos no deseados',
      'Preservativo',
      'Otros métodos anticonceptivos',
      'Cómo saber cuándo estaré preparado para mantener relaciones sexuales',
    ],
    levels: ['Nada', 'Casi nada', 'Más o menos', 'Bastante', 'Mucho'],
    nextStep: 13,
  },
  {
    id: 13,
    text: 'Responde a las siguientes preguntas de Verdadero o Falso:',
    type: 'checkbox',
    field: 'true_false_questions',
    options: [
      { label: 'La marcha atrás es un método bastante seguro', value: 'statement_1' },
      { label: 'Si se lava con cuidado podemos usar el preservativo varias veces', value: 'statement_2' },
      { label: 'Para utilizar anticonceptivos hormonales se ha de acudir a un centro sanitario', value: 'statement_3' },
      { label: 'Tener relaciones sexuales completas (con penetración) durante la regla minimiza el riesgo de embarazo', value: 'statement_4' },
      { label: 'Las pastillas anticonceptivas son eficaces si se toman antes de cada relación', value: 'statement_5' },
      { label: 'Tomar la píldora protege frente a las ITS', value: 'statement_6' },
      { label: 'El único método anticonceptivo que protege de las ITS es el preservativo', value: 'statement_7' },
      { label: 'Si la persona con la que mantengo relaciones sexuales tiene una higiene adecuada hay poca probabilidad de que me contagie una ITS', value: 'statement_8' },
      { label: 'EL VIH y VHC (Virus de la Hepatitis C) solo se transmiten a través de relaciones sexuales', value: 'statement_9' }
    ],
    nextStep: 22,
  },  
  {
    id: 22,
    text: '¿Sabes qué es la PrEP (profilaxis pre-exposición)?',
    type: 'radio',
    field: 'knows_prep',
    options: [
      { label: 'Sí', value: 'yes' },
      { label: 'No', value: 'no' },
    ],
    nextStep: (value: string) => (value === 'yes' ? 23 : 24),
  },
  {
    id: 23,
    text: 'Escribe todas las ITS (Infecciones de Transmisión Sexual) que conozcas:',
    type: 'text',
    field: 'known_stis',
    nextStep: 24,
  },
  {
    id: 24,
    text: 'De las siguientes infecciones de transmisión sexual, marca cuáles son curables:',
    type: 'checkbox',
    field: 'curable_stis',
    options: [
      { label: 'Sífilis', value: 'syphilis' },
      { label: 'Hepatitis B', value: 'hepatitis_b' },
      { label: 'Clamidiasis', value: 'chlamydia' },
      { label: 'Herpes', value: 'herpes' },
      { label: 'Virus del papiloma humano (VPH)', value: 'hpv' },
      { label: 'Gonorrea', value: 'gonorrhea' },
      { label: 'Tricomoniasis', value: 'trichomoniasis' },
      { label: 'VIH', value: 'hiv' },
    ],
    nextStep: 25,
  },
  {
    id: 25,
    text: 'Escribe todos los métodos anticonceptivos que conozcas:',
    type: 'text',
    field: 'known_contraceptives',
    nextStep: 26,
  },
  {
    id: 26,
    text: 'Escribe todos los métodos de protección de ITS que conozcas:',
    type: 'text',
    field: 'known_sti_protection',
    nextStep: 27,
  },
  {
    id: 27,
    text: 'Marca en qué medida te parece que estos comportamientos en una relación de pareja constituyen abuso o maltrato:',
    type: 'matrix',
    field: 'abuse_indicators',
    topics: [
      'Controlar las redes sociales de la pareja',
      'Decidir con quién puede salir',
      'Revisar el móvil sin permiso',
      'Exigir saber dónde está en todo momento',
      'Criticar su forma de vestir',
      'Mostrar celos frecuentemente',
    ],
    levels: ['Nada', 'Poco', 'Moderado', 'Bastante', 'Totalmente'],
    nextStep: 28,
  }
];
